# Generated by Django 4.2 on 2024-07-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.123rf.com/photo_144724058_a-plate-full-of-capsules-and-tablets-of-different-shapes-and-sizes-with-knife-and-fork.html', max_length=500),
        ),
    ]
